2018-12-10 19:37:29,698 ERROR: Exception on /explore [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/T1/app/main/routes.py", line 66, in explore
    prev_url=prev_url)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/T1/app/templates/garage.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/pi/T1/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/pi/T1/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/pi/T1/app/templates/garage.html", line 10, in block "app_content"
    {% include '_post.html' %}
  File "/home/pi/T1/app/templates/_post.html", line 5, in top-level template code
    <img src="{{ post.author.avatar(70) }}" />
UndefinedError: 'None' has no attribute 'avatar'
2018-12-10 19:38:11,789 INFO: Microblog startup [in /home/pi/T1/app/__init__.py:80]
2018-12-10 19:48:52,137 INFO: Microblog startup [in /home/pi/T1/app/__init__.py:80]
2018-12-10 19:52:15,346 INFO: Microblog startup [in /home/pi/T1/app/__init__.py:80]
2018-12-10 19:52:44,596 INFO: Microblog startup [in /home/pi/T1/app/__init__.py:80]
2018-12-10 19:52:52,207 ERROR: Exception on /explore [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/T1/app/main/routes.py", line 66, in explore
    prev_url=prev_url)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/T1/app/templates/garage.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/pi/T1/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/usr/local/lib/python2.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/pi/T1/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/pi/T1/app/templates/garage.html", line 10, in block "app_content"
    {% include '_post.html' %}
  File "/home/pi/T1/app/templates/_post.html", line 5, in top-level template code
    <img src="{{ post.author.avatar(70) }}" />
UndefinedError: 'None' has no attribute 'avatar'
2018-12-10 19:54:05,162 INFO: Microblog startup [in /home/pi/T1/app/__init__.py:80]
2018-12-10 20:01:24,325 INFO: Microblog startup [in /home/pi/T1/app/__init__.py:80]
2018-12-10 20:03:25,207 INFO: Microblog startup [in /home/pi/T1/app/__init__.py:80]
2018-12-10 20:04:29,713 INFO: Microblog startup [in /home/pi/T1/app/__init__.py:80]
2018-12-11 02:37:25,134 INFO: Microblog startup [in /home/pi/T1/app/__init__.py:80]
2018-12-11 02:41:23,143 INFO: Microblog startup [in /home/pi/T1/app/__init__.py:80]
2018-12-11 02:57:03,080 INFO: Microblog startup [in /home/pi/T1/app/__init__.py:80]
2018-12-11 03:03:25,354 INFO: Microblog startup [in /home/pi/T1/app/__init__.py:80]
2018-12-11 03:05:00,594 INFO: Microblog startup [in /home/pi/T1/app/__init__.py:80]
2018-12-11 15:43:31,699 INFO: Microblog startup [in /home/pi/T1/app/__init__.py:80]
